
[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/Lambda-NIC/faas-provider"
  version = "0.6.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "go.etcd.io/etcd"
  version = "3.3.10"

[[constraint]]
  name = "github.com/Lambda-NIC/faas-netes"
  version = "0.6.4"

[[constraint]]
  name = "github.com/Lambda-NIC/faas"
  version = "0.9.11"
