
[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/Lambda-NIC/faas-provider"
  revision = "0f135d552e5df242cbbef5d980fcd8a498ba4833"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "go.etcd.io/etcd"
  version = "3.3.10"

[[constraint]]
  name = "github.com/Lambda-NIC/faas-netes"
  revision = "142773143c15c31ade9f136aab86dc14efb9761c"

[[constraint]]
  name = "github.com/Lambda-NIC/faas"
  version = "0.9.11"
