apiVersion: v1
description: Enable Kubernetes as a backend for OpenFaaS (Functions as a Service)
name: openfaas
version: 1.5.0
sources:
- https://github.com/Lambda-NIC/faas
- https://github.com/Lambda-NIC/faas-netes
home: https://www.openfaas.com
icon: https://raw.githubusercontent.com/openfaas/media/master/OpenFaaS_logo_stacked_opaque.png
keywords:
- functions
- service
maintainers:
- name: alexellis
  email: alex@openfaas.com
- name: rimusz
  email: rmocius@gmail.com
- name: stefanprodan
  email: stefan.prodan@gmail.com
